name: EdgeTyper — CI pipeline

on:
  push:
    branches: [ restructured ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: edgetyper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package + deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pandas networkx numpy requests

      - name: Fetch OpenTelemetry Demo
        run: git clone --depth=1 https://github.com/open-telemetry/opentelemetry-demo.git otel-demo

      - name: Start OpenTelemetry Demo (Docker Compose)
        working-directory: otel-demo
        run: docker compose up --detach --force-recreate --remove-orphans

      - name: Wait until demo is ready (Envoy :8080 + Jaeger UI)
        run: |
          set -euo pipefail
          for i in {1..60}; do curl -fsS http://localhost:8080/ >/dev/null && break || sleep 2; done
          for i in {1..60}; do curl -fsS http://localhost:8080/jaeger/ui/ >/dev/null && break || sleep 2; done

      - name: Run EdgeTyper pipeline (all stages)
        env:
          RUN_ID: ${{ github.run_id }}
          SKIP_CHAOS: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        run: bash scripts/entrypoint.sh

      - name: Upload run artifact
        uses: actions/upload-artifact@v4
        with:
          name: edgetyper-${{ github.run_id }}
          path: runs/${{ github.run_id }}/

      - name: Setup Pages
        if: always() #'refs/heads/main'
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        if: always() #github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: runs/${{ github.run_id }}/
      - name: Deploy to Pages
        if: always() #github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

      - name: Tear down demo
        if: always()
        working-directory: otel-demo
        run: docker compose down -v
